# NEGA Configuration File
#
# Overview:
# This configuration file is a critical component of the NEGA pipeline.
# It specifies the parameters necessary for the evaluation command across various settings
# using data configurations derived from the original OMIM matrix.
#
# The optimization parameters below control key aspects of the training process:
#
# - regularization_parameter (float): Regulates the strength of the regularization term to prevent overfitting.
# - side_info_regularization (float): Regularization term on the regression term.
# - symmetry_parameter (float): Quantify the asymmetry  of the bregman distance.
# - smoothness_parameter (float): Sets the initial smoothness of the optimization landscape, influencing the step size.
# - rho_increase (float): Determines the factor by which the step size is increased dynamically during training for acceleration.
# - rho_decrease (float): Specifies the factor for decreasing the step size to help stabilize convergence.
#
"default":
  regularization_parameters: 
    "λd": 0.003
    "λg": 0.019
  symmetry_parameter: 0.99
  smoothness_parameter: 0.001
  rho_increase: 5.0
  rho_decrease: 0.9
"enega":
  regularization_parameters: 
    "λd": 0.00063
    "λg": 0.0466
    "λG": 0.000478
  symmetry_parameter: 0.99
  smoothness_parameter: 0.001
  rho_increase: 5.0
  rho_decrease: 0.9
"nega-fs":
  regularization_parameters: 
    "λd": 0.003
    "λg": 0.019
  symmetry_parameter: 0.99
  smoothness_parameter: 0.001
  rho_increase: 5.0
  rho_decrease: 0.9
"nega-reg":
  regularization_parameters: 
    "λd": 21.
    "λg": 0.00028
    "λ_βd": 27.
    "λ_βg": 80.
  symmetry_parameter: 0.99
  smoothness_parameter: 0.001
  rho_increase: 5.0
  rho_decrease: 0.9
