# NEGA Configuration File
#
# Overview:
# This configuration file is a critical component of the NEGA pipeline.
# It specifies the parameters necessary for the evaluation command across various settings
# using data configurations derived from the original OMIM matrix.
#
# The optimization parameters below control key aspects of the training process:
#
# - regularization_parameter (float): Regulates the strength of the regularization term to prevent overfitting.
# - side_info_regularization (float): Regularization term on the regression term.
# - symmetry_parameter (float): Quantify the asymmetry  of the bregman distance.
# - smoothness_parameter (float): Sets the initial smoothness of the optimization landscape, influencing the step size.
# - rho_increase (float): Determines the factor by which the step size is increased dynamically during training for acceleration.
# - rho_decrease (float): Specifies the factor for decreasing the step size to help stabilize convergence.
#
"ones-only":
  regularization_parameter: 37.15434002668561
  symmetry_parameter: 0.99
  smoothness_parameter: 0.001
  rho_increase: 2.0
  rho_decrease: 0.8
"with-zeros":
  regularization_parameter: 81.13657034677068
  symmetry_parameter: 0.99
  smoothness_parameter: 0.001
  rho_increase: 5.0
  rho_decrease: 0.6
"side-info-imc":
  regularization_parameter: 0.055902850864821545
  symmetry_parameter: 0.99
  smoothness_parameter: 0.001
  rho_increase: 2.0
  rho_decrease: 0.7
"side-info-genehound":
  side_info_regularization: 9.913754777623938
  regularization_parameter: 6.403938201080584
  symmetry_parameter: 0.99
  smoothness_parameter: 0.001
  rho_increase: 6.0
  rho_decrease: 0.8
