# NEGA Configuration File
#
# Overview:
# This configuration file is a critical component of the NEGA pipeline.
# It specifies the parameters necessary for the evaluation command across various settings
# using data configurations derived from the original OMIM matrix.
#
# The optimization parameters below control key aspects of the training process:
#
# - regularization_parameter (float): Regulates the strength of the regularization term to prevent overfitting.
# - side_info_regularization (float): Regularization term on the link matrices.
# - symmetry_parameter (float): Adjusts the gradient update to ensure symmetric behavior in the optimization process.
# - smoothness_parameter (float): Sets the initial smoothness of the optimization landscape, influencing convergence.
# - rho_increase (float): Determines the factor by which the step size is increased dynamically during training for acceleration.
# - rho_decrease (float): Specifies the factor for decreasing the step size to help stabilize convergence.
#
"ones-only":
  regularization_parameter: 1.398e-03
  symmetry_parameter: 1.349e-04
  smoothness_parameter: 1.496e-02
  rho_increase: 7.0
  rho_decrease: 0.3
"with-zeros":
  regularization_parameter: 3.397e-03
  symmetry_parameter: 1.246e-02
  smoothness_parameter: 1.679e-02
  rho_increase: 10.0
  rho_decrease: 0.3
"side-info-imc":
  regularization_parameter: 6.690e-05
  symmetry_parameter: 5.448e-05
  smoothness_parameter: 1.000e-05
  rho_increase: 7.0
  rho_decrease: 0.7
"side-info-genehound":
  regularization_parameter: 8.463e-01
  side_info_regularization: 7.871e-01
  symmetry_parameter: 1.163e-05
  smoothness_parameter: 1.141e-05
  rho_increase: 2.0
  rho_decrease: 0.5