# NEGA Configuration File
#
# Overview:
# This configuration file is a critical component of the NEGA pipeline.
# It specifies the parameters necessary for the evaluation command across various settings
# using data configurations derived from the original OMIM matrix.
#
# The optimization parameters below control key aspects of the training process:
#
# - regularization_parameter (float): Regulates the strength of the regularization term to prevent overfitting.
# - side_info_regularization (float): Regularization term on the link matrices.
# - symmetry_parameter (float): Adjusts the gradient update to ensure symmetric behavior in the optimization process.
# - smoothness_parameter (float): Sets the initial smoothness of the optimization landscape, influencing convergence.
# - rho_increase (float): Determines the factor by which the step size is increased dynamically during training for acceleration.
# - rho_decrease (float): Specifies the factor for decreasing the step size to help stabilize convergence.
#
"ones-only":
  regularization_parameter: 1.0e-03
  symmetry_parameter: 1.0e-04
  smoothness_parameter: 1.0e-02
  rho_increase: 7.0
  rho_decrease: 0.3
"with-zeros":
  regularization_parameter: 1.0e-03
  symmetry_parameter: 1.0e-02
  smoothness_parameter: 1.0e-02
  rho_increase: 10.0
  rho_decrease: 0.3
"side-info-imc":
  regularization_parameter: .0002114853485716427
  symmetry_parameter: 0.916702252328461
  smoothness_parameter: 1.824500300021557e-05
  rho_increase: 3.0
  rho_decrease: 0.3
"side-info-genehound":
  side_info_regularization: 1.0e+01
  regularization_parameter: 1.0e+01
  symmetry_parameter: 0.99
  smoothness_parameter: 1.0e+03
  rho_increase: 4.0
  rho_decrease: 0.8
