# NEGA Configuration File
#
# Overview:
# This configuration file is a critical component of the NEGA pipeline.
# It specifies the parameters necessary for the evaluation command across various settings
# using data configurations derived from the original OMIM matrix.
#
# The optimization parameters below control key aspects of the training process:
#
# - regularization_parameter (float): Regulates the strength of the regularization term to prevent overfitting.
# - side_info_regularization (float): Regularization term on the regression term.
# - symmetry_parameter (float): Quantify the asymmetry  of the bregman distance.
# - lipschitz_smoothness (float): Sets the initial smoothness of the optimization landscape, influencing the step size.
# - rho_increase (float): Determines the factor by which the step size is increased dynamically during training for acceleration.
# - rho_decrease (float): Specifies the factor for decreasing the step size to help stabilize convergence.
#
"default":
  regularization_parameters:
    'λg': 2.3640269928962176
    'λd': 1.025185994119589
  symmetry_parameter: 0.99
  lipschitz_smoothness: 0.001
  rho_increase: 2.0
  rho_decrease: 0.1
"enega":
  regularization_parameters:
    'λg': 2.3640269928962176
    'λd': 1.025185994119589
    'λG': 10.0001065934080
  symmetry_parameter: 0.99
  lipschitz_smoothness: 0.001
  rho_increase: 2.0
  rho_decrease: 0.1
"nega-fs":
  regularization_parameters: 
    'λg': 2.2369764111729826
    'λd': 0.00017700604520052838
  symmetry_parameter: 0.99
  lipschitz_smoothness: 0.001
  rho_increase: 2.0
  rho_decrease: 0.1
"nega-reg":
  regularization_parameters: 
    'λg': 65.75433290710455
    'λd': 73.48537777348042
    'λ_βg': 1.4405574444604472
    'λ_βd': 2.571487098041742
  symmetry_parameter: 0.99
  lipschitz_smoothness: 0.001
  rho_increase: 2.0
  rho_decrease: 0.1
