# NEGA Configuration File
#
# Overview:
# This configuration file is a critical component of the NEGA pipeline.
# It specifies the parameters necessary for the evaluation command across various settings
# using data configurations derived from the original OMIM matrix.
#
# The optimization parameters below control key aspects of the training process:
#
# - regularization_parameter (float): Regulates the strength of the regularization term to prevent overfitting.
# - symmetry_parameter (float): Adjusts the gradient update to ensure symmetric behavior in the optimization process.
# - smoothness_parameter (float): Sets the initial smoothness of the optimization landscape, influencing convergence.
# - rho_increase (float): Determines the factor by which the step size is increased dynamically during training for acceleration.
# - rho_decrease (float): Specifies the factor for decreasing the step size to help stabilize convergence.
#
# Usage Guidelines:
# 1. Choose the appropriate data configuration ("1s", "0s", or "side info") based on your experimental needs.
# 2. Fine-tune these parameters to match your dataset and objectives.
# 3. Confirm that the settings are aligned with your experimental design before running the evaluation.
# 4. Adapt and extend this file as necessary to explore the impact of different configurations on model performance.
#
"1s":
  regularization_parameter: 0.00139879
  symmetry_parameter: 0.00013496
  smoothness_parameter: 0.01496
  rho_increase: 7
  rho_decrease: 0.3
"0s":
  regularization_parameter: 0.00339788
  symmetry_parameter: 0.0124692
  smoothness_parameter: 0.0167905
  rho_increase: 10
  rho_decrease: 0.3
"side-info":
  regularization_parameter: 0.000442003
  symmetry_parameter: 0.00862493
  smoothness_parameter: 4.3241e-05
  rho_increase: 4
  rho_decrease: 0.2
